//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationModelRelease) DeepCopyInto(out *AuthorizationModelRelease) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationModelRelease.
func (in *AuthorizationModelRelease) DeepCopy() *AuthorizationModelRelease {
	if in == nil {
		return nil
	}
	out := new(AuthorizationModelRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthorizationModelRelease) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationModelReleaseList) DeepCopyInto(out *AuthorizationModelReleaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AuthorizationModelRelease, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationModelReleaseList.
func (in *AuthorizationModelReleaseList) DeepCopy() *AuthorizationModelReleaseList {
	if in == nil {
		return nil
	}
	out := new(AuthorizationModelReleaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthorizationModelReleaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationModelReleaseSpec) DeepCopyInto(out *AuthorizationModelReleaseSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationModelReleaseSpec.
func (in *AuthorizationModelReleaseSpec) DeepCopy() *AuthorizationModelReleaseSpec {
	if in == nil {
		return nil
	}
	out := new(AuthorizationModelReleaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationModelReleaseState) DeepCopyInto(out *AuthorizationModelReleaseState) {
	*out = *in
	in.PublishedAt.DeepCopyInto(&out.PublishedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationModelReleaseState.
func (in *AuthorizationModelReleaseState) DeepCopy() *AuthorizationModelReleaseState {
	if in == nil {
		return nil
	}
	out := new(AuthorizationModelReleaseState)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationModelReleaseStatus) DeepCopyInto(out *AuthorizationModelReleaseStatus) {
	*out = *in
	if in.Stable != nil {
		in, out := &in.Stable, &out.Stable
		*out = new(AuthorizationModelReleaseState)
		(*in).DeepCopyInto(*out)
	}
	if in.Candidate != nil {
		in, out := &in.Candidate, &out.Candidate
		*out = new(AuthorizationModelReleaseState)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationModelReleaseStatus.
func (in *AuthorizationModelReleaseStatus) DeepCopy() *AuthorizationModelReleaseStatus {
	if in == nil {
		return nil
	}
	out := new(AuthorizationModelReleaseStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationModule) DeepCopyInto(out *AuthorizationModule) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationModule.
func (in *AuthorizationModule) DeepCopy() *AuthorizationModule {
	if in == nil {
		return nil
	}
	out := new(AuthorizationModule)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthorizationModule) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationModuleList) DeepCopyInto(out *AuthorizationModuleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AuthorizationModule, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationModuleList.
func (in *AuthorizationModuleList) DeepCopy() *AuthorizationModuleList {
	if in == nil {
		return nil
	}
	out := new(AuthorizationModuleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AuthorizationModuleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationModuleSpec) DeepCopyInto(out *AuthorizationModuleSpec) {
	*out = *in
	if in.Topology != nil {
		in, out := &in.Topology, &out.Topology
		*out = make(map[string]TopologyRelation, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make(map[string]AuthorizationRole, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Permissions != nil {
		in, out := &in.Permissions, &out.Permissions
		*out = make(map[string]AuthorizationPermission, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationModuleSpec.
func (in *AuthorizationModuleSpec) DeepCopy() *AuthorizationModuleSpec {
	if in == nil {
		return nil
	}
	out := new(AuthorizationModuleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationModuleStatus) DeepCopyInto(out *AuthorizationModuleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationModuleStatus.
func (in *AuthorizationModuleStatus) DeepCopy() *AuthorizationModuleStatus {
	if in == nil {
		return nil
	}
	out := new(AuthorizationModuleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationPermission) DeepCopyInto(out *AuthorizationPermission) {
	*out = *in
	if in.AnyOf != nil {
		in, out := &in.AnyOf, &out.AnyOf
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationPermission.
func (in *AuthorizationPermission) DeepCopy() *AuthorizationPermission {
	if in == nil {
		return nil
	}
	out := new(AuthorizationPermission)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationRole) DeepCopyInto(out *AuthorizationRole) {
	*out = *in
	if in.Subjects != nil {
		in, out := &in.Subjects, &out.Subjects
		*out = make([]AuthorizationSubject, len(*in))
		copy(*out, *in)
	}
	if in.Inherited != nil {
		in, out := &in.Inherited, &out.Inherited
		*out = make([]InheritedRelation, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationRole.
func (in *AuthorizationRole) DeepCopy() *AuthorizationRole {
	if in == nil {
		return nil
	}
	out := new(AuthorizationRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorizationSubject) DeepCopyInto(out *AuthorizationSubject) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorizationSubject.
func (in *AuthorizationSubject) DeepCopy() *AuthorizationSubject {
	if in == nil {
		return nil
	}
	out := new(AuthorizationSubject)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InheritedRelation) DeepCopyInto(out *InheritedRelation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InheritedRelation.
func (in *InheritedRelation) DeepCopy() *InheritedRelation {
	if in == nil {
		return nil
	}
	out := new(InheritedRelation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TopologyRelation) DeepCopyInto(out *TopologyRelation) {
	*out = *in
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TopologyRelation.
func (in *TopologyRelation) DeepCopy() *TopologyRelation {
	if in == nil {
		return nil
	}
	out := new(TopologyRelation)
	in.DeepCopyInto(out)
	return out
}
