---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - auth.bridder.io
  resources:
  - authorizationmodelreleases
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auth.bridder.io
  resources:
  - authorizationmodelreleases/status
  - authorizationmodules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - auth.bridder.io
  resources:
  - authorizationmodules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auth.bridder.io
  resources:
  - authorizationmodules/finalizers
  verbs:
  - update
