apiVersion: auth.bridder.io/v1
kind: AuthorizationModule
metadata:
  labels:
    app.kubernetes.io/name: bridder
    app.kubernetes.io/managed-by: kustomize
  name: user-authorization
  namespace: core
spec:
  resource: user
---
apiVersion: auth.bridder.io/v1
kind: AuthorizationModule
metadata:
  labels:
    app.kubernetes.io/name: bridder
    app.kubernetes.io/managed-by: kustomize
  name: namespace-authorization
  namespace: auth
spec:
  resource: namespace
  roles:
    owner:
      subjects:
        - type: user
    operator:
      subjects:
        - type: user
      inherited:
        - relation: owner
    reader:
      subjects:
        - type: user
      inherited:
        - relation: operator

  permissions:
    can_view:
      anyOf:
        - reader
    can_delete:
      anyOf:
        - owner
    can_manage_roles:
      anyOf:
        - owner
    can_edit:
      anyOf:
        - operator
    can_create_scope:
      anyOf:
        - operator
---
apiVersion: auth.bridder.io/v1
kind: AuthorizationModule
metadata:
  labels:
    app.kubernetes.io/name: bridder
    app.kubernetes.io/managed-by: kustomize
  name: scope-authorization
  namespace: auth
spec:
  resource: scope
  topology:
    parent:
      resources:
        - namespace
  roles:
    owner:
      inherited:
        - relation: owner
          via: parent
    operator:
      inherited:
        - relation: operator
          via: parent
    reader:
      inherited:
        - via: parent
          relation: reader
    accessor:
      subjects:
        - type: user

  permissions:
    can_view:
      anyOf:
        - reader
    can_delete:
      anyOf:
        - operator
    can_manage_roles:
      anyOf:
        - operator
    can_edit:
      anyOf:
        - operator
    can_access:
      anyOf:
        - accessor
