apiVersion: auth.bridder.io/v1
kind: AuthorizationModule
metadata:
  labels:
    app.kubernetes.io/name: bridder
    app.kubernetes.io/managed-by: kustomize
  name: group-authorization
spec:
  resource: group
  roles:
    member:
      subjects:
        - type: user
---
apiVersion: auth.bridder.io/v1
kind: AuthorizationModule
metadata:
  labels:
    app.kubernetes.io/name: bridder
    app.kubernetes.io/managed-by: kustomize
  name: organization-authorization
spec:
  resource: organization
  roles:
    owner:
      subjects:
        - type: user
---
apiVersion: auth.bridder.io/v1
kind: AuthorizationModule
metadata:
  labels:
    app.kubernetes.io/name: bridder
    app.kubernetes.io/managed-by: kustomize
  name: project-authorization
spec:
  resource: project
  topology:
    parent:
      resources:
        - organization
  roles:
    owner:
      subjects:
        - type: user
    editor:
      subjects:
        - type: user
        - type: group
          relation: member
    viewer:
      inherited:
        - via: parent
          relation: owner
  permissions:
    view:
      anyOf:
        - owner
        - editor
        - viewer
    delete:
      anyOf:
        - owner
