apiVersion: apps/v1
kind: Deployment
metadata:
  name: openfga
  labels:
    app.kubernetes.io/name: openfga
    app.kubernetes.io/component: authorization-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: openfga
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openfga
        app.kubernetes.io/component: authorization-server
    spec:
      containers:
      - name: openfga
        image: openfga/openfga:v1.16.0
        args:
        - run
        - --experimentals=authzen
        env:
        - name: OPENFGA_LOG_FORMAT
          value: json
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: grpc
          containerPort: 8081
          protocol: TCP
        - name: playground
          containerPort: 3000
          protocol: TCP
        readinessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: openfga
  labels:
    app.kubernetes.io/name: openfga
    app.kubernetes.io/component: authorization-server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: openfga
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  - name: grpc
    port: 8081
    targetPort: grpc
    protocol: TCP
  - name: playground
    port: 3000
    targetPort: playground
    protocol: TCP
