apiVersion: v1
kind: Secret
metadata:
  name: config
  labels:
    app.kubernetes.io/name: bridder
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  OPENFGA_API_URL: http://bridder-openfga:8080
  OPENFGA_STORE_NAME: bridder
  NATS_URL: nats://bridder-nats:4222
