apiVersion: v1
kind: Secret
metadata:
  name: config
  labels:
    app.kubernetes.io/name: authz-operator
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  OPENFGA_API_URL: http://authz-operator-openfga:8080
  OPENFGA_STORE_NAME: authz-operator
